name: ${project.name}
version: ${project.version}
main: ${package}
author: "Felux"
website: https://felux.io/
description: ${project.descriptionó}
softdepend: ["PlaceholderAPI", "WorldGuard"]

commands:
  feluxitems:
    aliases: ["fitems", "vouchers", "coupons"]